name: quadernodicampo
favicon: null
layout_spectrum: 0.6769228978082538
typography_spectrum: 0.7035685835871845
title: Quadernodicampo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5083457548171282
  lightness: 0.40687584807164967
  saturation: 0.10710880649276078
  rhythmicContrast: 0.15091719408519566
purpose: []
