name: quadernodicampo
favicon: null
layout_spectrum: 0
typography_spectrum: 0.30128
title: Quadernodicampo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e2e0e1'
    - '#a6a9ac'
    - '#666b71'
    - '#3b3b3b'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
